
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            scope: openid

        provider:
          keycloak:
            issuer-uri: ${oauth2.client.keycloak}/realms/${client-realm}
            user-name-attribute: preferred_username

      resource-server:
          jwt:
            issuer-uri: ${oauth2.client.keycloak}/realms/${client-realm}

log:
  org.springframework.web: TRACE
  com.siukatech.poc: TRACE


